### ISSUE TITLE
nlp-scraper subject conflicting instructions

### ISSUE THREAD

**Issue by jarmo-seljamaa** [01-edu/public#2390]
nlp-scraper
---
The task instructs [to build a data scraper](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper#scrapper). Well, it says we should find a news site that is easy to "scrap" not "scrape", but I guess this isn't a task of cybersecurity but just another misspelling (alongside with calling the whole thing a "scrapper" instead of "scraper"). But nevertheless it suggests we can choose any news site.

Then in the [topic detection](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper#2-topic-detection) instruction it says:
> The goal is to detect what the article is dealing with: Tech, Sport, Business, Entertainment or Politics. To do so, a labelled dataset is provided. 

The given list of these 5 topics (Tech, Sport, Business, Entertainment or Politics) means that we cannot choose just any site. For example if I chose a tech news site, there would be no Sports or Politics news there to be found.

Furthermore, the sentence `a labelled dataset is provided` suggests that some datafiles are provided on the platform. I cannot find any links, but apparently there are two CSV files included in the public repo.

![image](https://github.com/01-edu/public/assets/80747520/2e4bf5d7-0df9-4313-8eec-ee1720a1f329)

So which is it? Should we scrape our own data and therefore also use our own list of topics that are provided with this scraped data (as categories or tags), or should we use the provided data files?

If we build our own scraper, then these instructions are insufficient:
> from the last week otherwise the volume may be to high

News sites vary a lot in the volume of the news per day. The task description requires summaries by day for a week full of content. So it would be great if an idea would be given how many articles per day would be a good fit to get meaningful results, is it 50, 100, 300 or 500 per day?

EDIT: The [Deliverables](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper#deliverables) section suggests the scraper should fetch at least 300 results. Why not make it clear already in the scraper instructions?

**Comment by jarmo-seljamaa** [comment]
Also the scraping instructions seem to be somewhat off:

> - Store it:
>   - File system per day:
>      -  URL, date unique id
>      -  headline
>      -  body of the article
>   - SQL database (optional)

It's unclear why we are instructed to store the scraped data 'per day'. It makes much more sense to combine it all in one single datafile, as also shown in the [deliverables](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper#deliverables) part: the `topic_classification_data.csv` is a single file and there are no separate files "per day".

Furthermore, I believe the intended data file structure might be:

- Data file structure
  - URL
  - date
  - unique ID
  - headline
  - body of the article

Currently the first 3 fields are awkwardly listed as one.

**Comment by jarmo-seljamaa** [comment]
After countless experiments I found it it nearly impossible to accomplish the model training goal:
> Learning constraints: Score on test: > 95%

The trouble with using our own scraped data is that not all sites categorize their articles choerently. In my case I used a news source where the classifier was doing a god job in half of the categories, but always failed in a few others, which were probably too broad or vague (categories like 'Life', 'Opinion' or 'Knowledge').

Then I tried to run my classifier pipeline on the `BBC News Test.csv` and realised that I had in fact already built a good classifier with accuracy score above the required 95%. It just was not able to build a model on my scraped data.

So am I right in guessing that the [topic detection](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper#2-topic-detection) instructions lack the references to the provided BBC News dataset and we are actually required to train our data on that?

**Comment by jarmo-seljamaa** [comment]
Next issue: the pickle files of the model as described in the [deliverables](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper#deliverables) cannot be pushed to our Gitea due to file size restrictions. It is only possible for the auditor to run the program to generate these pickle files, but they cannot check the compliance initially as described in the [first audit question](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper/audit#does-the-structure-of-the-project-look-like-the-above)

**Comment by jarmo-seljamaa** [comment]
What do you mean by this in [sentiment analysis](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper#3-sentiment-analysis) description?
> You already know how to train a sentiment analysis classifier ;-)

Is this a reference to some task that's not included in the AI branch? How should we know how to train a sentiment analysis classifier?

**Comment by jarmo-seljamaa** [comment]
Is there someone here that can answer these questions? I'm crying and pulling my hair trying to make sense of the task instructions and audit.

The last part of the [deliverables](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper#deliverables) shows an output of `python nlp_enriched_news.py`. 
- What does `Enriching <URL>:` mean???
- Which articles should be fed to this script??? 
- How many articles??? All 300??? Audit says [3 articles](https://github.com/01-edu/public/blob/master/subjects/ai/nlp-scraper/audit/README.md#nlp-engine-on-3-articles). But if 3 then which 3???
- What does `I strongly suggest to create a data structure (dictionary for example) to save all the intermediate result. Then, a boolean argument cache fetched the intermediate results when they are already computed.` mean??? Intermediate results of what???

**Comment by jarmo-seljamaa** [comment]
The last row of the expected output:
> `Environmental scandal detected for <entity>`

Should we calculate scandal distance for each ORG entity??? Display all of them??? The biggest score??? Either way it cannot be one single `Scandal_distance` in the dataframe... 

For educational purposes it would make much more sense if instead of just printing out the name of the entity, we'd have to print the sentence that scored most in scandal detection. That would help the auditor assess if the scandal was correctly detected.

**Comment by nprimo** [comment]
Hi @jarmo-seljamaa, thank you for all the feedback. I am looking into all the points you raised and I hope to clarify the subject asap

**Comment by nprimo** [comment]
@jarmo-seljamaa there will be one or more PR to fix the remaining issues not addressed in CON-2390

**Comment by jarmo-seljamaa** [comment]
I appreciate you updating the formatting and spelling of the task description as I can see in the PR, however these rarely address the clarity and coherence of the instructions.

> Find a news website that is easy to scrap. I could have chosen the website,

This suggestion is kind of "scrap" (you're still missing and E in that word). I scraped 4 different news sites during solving this task, and only the last of them worked somewhat OK with the project goal. As we are supposed to detect environmental scandals related to organizations, it is of utmost importance that the chosen news site potentially has such news. Tech news sites rarely have this kind of content, for example. So the criteria should not be "find a news site that is easy to scrape", but "find a news site that covers news about business and environment and is easy to scrape". Otherwise we're looking in a wrong place with our scandal detectors.

>  Store the following information either in one file per day or in a SQL

Why should we store the information one file per day? What's the point of that? It's an unnecessary hassle to separate the datafiles by day and then later combine them back for analysis. It's much more convenient to have all the scraped data in one single datafile. 


In the dataframe structure:

>   Date scraped (`date`)

What good value does the date of scraping provide regarding a news story? During scraping we saved the date of the article (i.e. the date of publication). Why can't we use that?

> I strongly suggest creating a data structure (dictionary for example) to save all the intermediate result. Then, a boolean argument `cache` fetched the intermediate results when they are already computed.

Intermediate results of what? A boolean argument of `cache` fetched results? I'm sure you're trying to help, but this is just random words that do not pass a meaning.

**Comment by nprimo** [comment]
@jarmo-seljamaa, thank you for all the feedback.

About the missing misspelled word, I will fix that. 

>  I scraped 4 different news sites during solving this task, and only the last of them worked somewhat OK with the project goal. As we are supposed to detect environmental scandals related to organizations, it is of utmost importance that the chosen news site potentially has such news. Tech news sites rarely have this kind of content, for example. So the criteria should not be "find a news site that is easy to scrape", but "find a news site that covers news about business and environment and is easy to scrape". Otherwise we're looking in a wrong place with our scandal detectors.

You have access to the whole subject text: it is good to start working on your task only after you fully understand the whole project goal. 
I agree it's a hard task to find a "proper" source of data, but that is the same if you would like to do a real-life project or a task for a company. That's a skill you should develop as well as being able to perform the data analysis.

> Why should we store the information one file per day? What's the point of that? It's an unnecessary hassle to separate the datafiles by day and then later combine them back for analysis. It's much more convenient to have all the scraped data in one single datafile.

For example, smaller-sized files, instead of big ones, are easy to handle (for example, if you're looking for `diff`, or are willing to use only the data for a specific date). I don't find this added instruction that complicated to implement looking at the overall project. Is there anything specifically annoying about this task that am I missing?

> What good value does the date of scraping provide regarding a news story? During scraping we saved the date of the article (i.e. the date of publication). Why can't we use that?

Things online might change: saving the date when you retrieved the specific information can be valued as the "screenshot" of that specific news at that specific point in time. For example, the article might change in the future and the date of the article might not.

> Intermediate results of what? A boolean argument of cache fetched results? I'm sure you're trying to help, but this is just random words that do not pass a meaning. 

I will see if I can make this suggestion clearer or I will remove it as you suggest.

**Comment by jarmo-seljamaa** [comment]
> You have access to the whole subject text: it is good to start working on your task only after you fully understand the whole project goal. I agree it's a hard task to find a "proper" source of data, but that is the same if you would like to do a real-life project or a task for a company. That's a skill you should develop as well as being able to perform the data analysis.

It wouldn't hurt to mention that in the instructions, would it?
 
> > Why should we store the information one file per day? What's the point of that? It's an unnecessary hassle to separate the datafiles by day and then later combine them back for analysis. It's much more convenient to have all the scraped data in one single datafile.
> 
> For example, smaller-sized files, instead of big ones, are easy to handle (for example, if you're looking for `diff`, or are willing to use only the data for a specific date). I don't find this added instruction that complicated to implement looking at the overall project. Is there anything specifically annoying about this task that am I missing?

The point is that if a task instructs you to do something ("store the information one file per day"), then it should be related to that task, there should be a reason for that, it should be useful later in the exercise. Using splits per day is only referenced in the optional [source analysis](https://github.com/01-edu/public/tree/master/subjects/ai/nlp-scraper#5-source-analysis-optional) but even there it can be easily achieved by other methods than saving scraped data in separate files.

This is a general issue with AI branch tasks. They are not on point and while some of the actions described can be useful in general, the task should focus only on actions that are relevant to the specific task. I've take courses on DataCamp, Coursera and CodeCademy and they never give instructions that are not specifically required for the task in hand.

> > What good value does the date of scraping provide regarding a news story? During scraping we saved the date of the article (i.e. the date of publication). Why can't we use that?
> 
> Things online might change: saving the date when you retrieved the specific information can be valued as the "screenshot" of that specific news at that specific point in time. For example, the article might change in the future and the date of the article might not.

Again - during scraping you instructed only to save the date of the article, not the date of scraping. So the instructions are inconsistent. And although I agree that the date of scraping can be very useful in some contexts, it should be clearly understandable for the student why it is relevant and used in this task. 

> > Intermediate results of what? A boolean argument of cache fetched results? I'm sure you're trying to help, but this is just random words that do not pass a meaning.
> 
> I will see if I can make this suggestion clearer or I will remove it as you suggest.

Thanks for the effort, no changes tho...?
